M48
; DRILL file {KiCad 7.0.5} date Sun Sep 24 23:37:04 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-24T23:37:04-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.85Y-1.8
X2.85Y-4.45
X2.85Y-5.45
X2.85Y-6.3
X4.4Y-2.4
X5.85Y-1.8
X5.85Y-4.45
X5.85Y-5.45
X5.85Y-6.3
T0
M30
